{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trunk-canton.fullname" . }}-offset
  labels:
    {{- include "trunk-canton.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
