// Used by `bin/canton run <scenario> -c /conf/remote.conf` inside the running container.
canton {
  remote-participants {
    p1 { ledger-api { address = localhost, port = 5011 }, admin-api { address = localhost, port = 5012 } }
    p2 { ledger-api { address = localhost, port = 5021 }, admin-api { address = localhost, port = 5022 } }
  }
  remote-sequencers {
    seq1 { public-api { address = localhost, port = 5001 }, admin-api { address = localhost, port = 5002 } }
    seq2 { public-api { address = localhost, port = 5101 }, admin-api { address = localhost, port = 5102 } }
  }
  remote-mediators {
    med1 { admin-api { address = localhost, port = 5202 } }
    med2 { admin-api { address = localhost, port = 5302 } }
  }
}
